version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building platform-api...
      - docker build -t $IMAGE_PREFIX/platform-api:latest code/control-plane/api
      - echo Building frontend...
      - docker build -t $IMAGE_PREFIX/frontend:latest code/control-plane/ui
  post_build:
    commands:
      - echo Pushing platform-api...
      - docker push $IMAGE_PREFIX/platform-api:latest
      - echo Pushing frontend...
      - docker push $IMAGE_PREFIX/frontend:latest
      - echo Build completed on $(date)
