CHATBOT_SYSTEM = "CHATBOT_SYSTEM"
WIREFRAME_SYSTEM = "WIREFRAME_SYSTEM"
DESIGNER_SYSTEM = "DESIGNER_SYSTEM"
MODIFY_SYSTEM = "MODIFY_SYSTEM"
WIREFRAME_CHAT = "WIREFRAME_CHAT"
DESIGN_CHAT = "DESIGN_CHAT"
SCREEN_CODEGEN = "SCREEN_CODEGEN"
REQUIREMENTS_SYNTHESIS = "REQUIREMENTS_SYNTHESIS"

ALL_SLOTS = [
    CHATBOT_SYSTEM,
    WIREFRAME_SYSTEM,
    DESIGNER_SYSTEM,
    MODIFY_SYSTEM,
    WIREFRAME_CHAT,
    DESIGN_CHAT,
    SCREEN_CODEGEN,
    REQUIREMENTS_SYNTHESIS,
]
